name: push
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.24
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go install ./...

      - name: Build image for tests
        run: make build_test

      - name: Run tests
        run: make test
