name: r2dtools
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUILD_ARCHIVE_NAME: "r2dtools-agent.tar.gz"
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.23
      id: go
      
    - name: Check out code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go install ./...

    - name: Build image for tests
      run: make build_test

    - name: Run tests
      run: make test

    - name: Build
      run: make build
        
    - name: Prepare build directory
      run: rm -rf build/.gitkeep
    
    - name: Create build archive
      run: tar -czvf $BUILD_ARCHIVE_NAME -C build/ .
    
    #- name: Deploy to server
    #  id: deploy
    #3  uses: Pendect/action-rsyncer@v1.1.0
    #  env:
    #    DEPLOY_KEY: ${{secrets.r2stDeploy}}
    #  with:
    #    flags: '-avz'
    #    options: ''
    #    ssh_options: ''
    #    src: $BUILD_ARCHIVE_NAME
    #    dest: 'root@134.0.115.60:/var/www/r2dtools.com/builds'
