name: sslbot
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUILD_ARCHIVE_NAME: "r2dtools-sslbot.tar.gz"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.24
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go install ./...

      - name: Build image for tests
        run: make build_test

      - name: Run tests
        run: make test

      - name: Build bot
        if: startsWith(github.ref, 'refs/tags/')
        run: make build version=${{  github.ref_name }}

      - name: Prepare build directory
        if: startsWith(github.ref, 'refs/tags/')
        run: rm -rf build/.gitkeep

      - name: Create build archive
        if: startsWith(github.ref, 'refs/tags/')
        run: tar -czvf $BUILD_ARCHIVE_NAME -C build/ .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: r2dtools-sslbot.tar.gz
