name: r2dtools
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUILD_ARCHIVE_NAME: "r2dtools-agent.tar.gz"
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.23
      id: go
      
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: go install ./...

    - name: Build image for tests
      run: make build_test

    - name: Run tests
      run: make test

    - name: Build agent
      run: make build
        
    - name: Prepare build directory
      run: rm -rf build/.gitkeep

    - name: Add build version
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        touch build/.version
        echo "${{  github.ref_name }}" >> build/.version

    - name: Create build archive
      run: tar -czvf $BUILD_ARCHIVE_NAME -C build/ .

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: r2dtools-agent.tar.gz
