name: release
on:
  release:
    types: [released]
env:
  IMAGE_VERSION: ${{ github.event.release.tag_name }}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      BUILD_ARCHIVE_NAME: "r2dtools-sslbot.tar.gz"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.24
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: go install ./...

      - name: Build bot
        run: |
          make build version=${{ env.IMAGE_VERSION }}
          rm -rf build/.gitkeep

      - name: Create build archive
        run: tar -czvf $BUILD_ARCHIVE_NAME -C build/ .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: r2dtools-sslbot.tar.gz
